### PR TITLE
Run curtin-ci on amd64 only, curtin-autoland-test run on all the archs

### PR DESCRIPTION
**Pull request by paride**

### CODE REVIEW

**Comment by powersj** [comment]
These basic tests do not take too long. Correct? As such I would prefer we run them on all architectures if we are capable of doing so at this point.

**Comment by paride** [comment]
Per standup discussion it's probably a better idea to:

1. run the curtin-ci job on amd64 only
2. run the curtin-autoland-test job on *all* the archs

In this way we'll minimize the job runs on non-amd64 machines, and have one final run that tests everything on all the archs.

**Comment by powersj** [comment]
ok +1

**Comment by paride** [comment]
This will require deleting the jobs from jenkins, as there is a change in the job type (matrix vs. "normal").

**Pull request merged**
