### PR TITLE
cloud-init: remove the autoland jobs

### PR DESCRIPTION
**Pull request by paride**
Not needed anymore as the cloud-init upstream repository is now hosted
on GitHub.

### CODE REVIEW

**Comment by paride** [comment]
After merging this the jobs are to be deleted manually.

**Comment by paride** [comment]
I think we're keeping it for the moment while we still have pending branches on Lauchpad. @blackboxsw do I remember correctly?

**Comment by paride** [comment]
In the meantime I deleted the jobs from the Jenkins UI, as they were noisy.

**Comment by OddBloke** [comment]
To be clear, I'm not blocking landing this on answering that question!

**Pull request merged**
